project:
  type: website

website:
  title: "My Lab Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: slides/slides.ipynb
        text: Slides

format:
  html:
    theme: cosmo
    toc: true